version: '3'
services:
  db:
    image: postgres:11
    environment:
      POSTGRES_DB: ${ET_DB_NAME}
      POSTGRES_USER: ${ET_DB_USER}
      POSTGRES_PASSWORD: ${ET_DB_PASS}

    ports:
    - ${ET_DB_PORT}:5432